- name: Deploy to Azure Storage
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az storage blob upload \
              --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} \
              --container-name '$web' \
              --file index.html \
              --name index.html \
              --overwrite true \
              --auth-mode key \
              --account-key $(az storage account keys list --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} --query '[0].value' -o tsv)
